import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, createHmac, timingSafeEqual, scryptSync, createHash } from 'node:crypto';
import { mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { storefrontPrivateToken } from './shopify-auth.js';

const root = dirname(fileURLToPath(import.meta.url));
const db = new DatabaseSync(process.env.AFFILIATE_DB || join(root, 'affiliate.sqlite'));
db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',code TEXT UNIQUE,kind TEXT DEFAULT 'tracking',rate_type TEXT DEFAULT 'none',rate REAL DEFAULT 0,created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applications(id INTEGER PRIMARY KEY,user_id INTEGER UNIQUE REFERENCES users(id),body TEXT NOT NULL,status TEXT DEFAULT 'pending',notes TEXT DEFAULT '',created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tokens(hash TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),purpose TEXT,expires INTEGER);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires INTEGER);
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),visitor TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS referral_sessions(hash TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires INTEGER);
CREATE TABLE IF NOT EXISTS orders(shopify_id TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL,updated TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS commissions(shopify_id TEXT PRIMARY KEY REFERENCES orders(shopify_id),user_id INTEGER REFERENCES users(id),amount REAL NOT NULL,status TEXT NOT NULL,updated TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,actor INTEGER,action TEXT,detail TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS outbox(id INTEGER PRIMARY KEY,recipient TEXT,subject TEXT,body TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agreements(version TEXT PRIMARY KEY,body TEXT NOT NULL,active INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS acceptance(user_id INTEGER REFERENCES users(id),version TEXT REFERENCES agreements(version),accepted TEXT DEFAULT CURRENT_TIMESTAMP,ip TEXT,PRIMARY KEY(user_id,version));
CREATE TABLE IF NOT EXISTS assets(id INTEGER PRIMARY KEY,title TEXT,category TEXT,url TEXT,status TEXT DEFAULT 'active',version INTEGER DEFAULT 1);`);
db.prepare('INSERT OR IGNORE INTO agreements(version,body,active) VALUES(?,?,1)').run('draft-1','Use only approved Saint Michaels Coffee materials. Do not change protected marks, make unauthorized claims, or imply endorsement. Disclose your affiliate relationship where required. Material can be withdrawn. This draft requires legal review.');
if (!db.prepare("SELECT 1 FROM users WHERE role='admin'").get()) {
  const email = process.env.ADMIN_EMAIL, pass = process.env.ADMIN_PASSWORD;
  if (!email || !pass || pass.length < 12) throw Error('Set ADMIN_EMAIL and ADMIN_PASSWORD (12+ characters) for initial setup');
  db.prepare("INSERT INTO users(email,name,password,role,status) VALUES(?,?,?,'admin','active')").run(email.toLowerCase(),'Administrator',hashPassword(pass));
}
const secret = process.env.SESSION_SECRET;
if (!secret || secret.length < 32) throw Error('Set SESSION_SECRET to 32+ random characters');
const q=(sql,...args)=>db.prepare(sql).get(...args), all=(sql,...args)=>db.prepare(sql).all(...args), run=(sql,...args)=>db.prepare(sql).run(...args);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sha=s=>createHash('sha256').update(s).digest('hex');
function hashPassword(p){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(p,salt,64).toString('hex')}`;}
function verifyPassword(p,stored){if(!stored)return false;const [salt,hex]=stored.split(':');return timingSafeEqual(scryptSync(p,salt,64),Buffer.from(hex,'hex'));}
function mail(to,subject,body){run('INSERT INTO outbox(recipient,subject,body) VALUES(?,?,?)',to,subject,body);}
function redirect(res,path,headers={}){res.writeHead(303,{Location:path,...headers});res.end();}
function page(res,title,content,code=200){res.writeHead(code,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff'});res.end(`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Saint Michaels Coffee</title><style>body{margin:0;background:#080e17;color:#f4f6fa;font:16px/1.5 system-ui}header,main{max-width:1050px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #294263}h1,h2{line-height:1.15}a{color:#a8d4ff}a.button,button{background:#2063a4;color:white;border:0;border-radius:5px;padding:11px 16px;cursor:pointer;text-decoration:none}input,select,textarea{box-sizing:border-box;width:100%;padding:11px;margin:5px 0 15px;border-radius:5px;border:1px solid #79869a;background:#111d2e;color:white}input[type=checkbox]{width:auto}label{display:block}article{padding:18px;margin:15px 0;background:#122033;border:1px solid #304969;border-radius:8px}small,.muted{color:#afbfcd}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #304969;text-align:left;padding:10px;vertical-align:top}nav a{margin-left:15px}form.inline{display:inline-block;margin:5px}form.inline input,form.inline select{width:auto} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}.scroll{overflow:auto}</style><header><strong>SAINT MICHAELS COFFEE · AFFILIATES</strong><nav><a href="/affiliate">Home</a><a href="/affiliate/dashboard">Dashboard</a><a href="/admin/affiliates">Admin</a></nav></header><main>${content}</main></html>`);}
function cookie(req){return /(?:^|; )sm_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];}
function current(req){const c=cookie(req);if(!c)return null;return q('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.hash=? AND sessions.expires>?',sha(c),Date.now());}
function login(res,user){const token=randomBytes(32).toString('hex');run('INSERT INTO sessions(hash,user_id,expires) VALUES(?,?,?)',sha(token),user.id,Date.now()+7*86400000);redirect(res,user.role==='admin'?'/admin/affiliates':'/affiliate/dashboard',{'Set-Cookie':`sm_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`});}
async function body(req){let raw='';for await(const b of req){raw+=b;if(raw.length>100000)throw Error('Request too large');}return raw;}
function form(raw){return Object.fromEntries(new URLSearchParams(raw));}
function requireRole(res,user,role){if(!user||user.role!==role||user.status!=='active'){page(res,'Access denied','<h1>Sign in with an authorized account</h1><a href="/affiliate/login">Sign in</a>',403);return false;}return true;}
function audit(user,action,detail){run('INSERT INTO audit(actor,action,detail) VALUES(?,?,?)',user?.id||null,action,JSON.stringify(detail));}
function field(label,name,type='text',required=false){return `<label>${esc(label)}<input name="${esc(name)}" type="${esc(type)}" ${required?'required':''}></label>`;}
function select(name,options){return `<select name="${name}">${options.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;}
function safePath(s){try{const u=new URL(s,'https://saintmichaelscoffee.com');return u.origin==='https://saintmichaelscoffee.com'&&['/','/shop.html','/foundation.html','/about.html'].includes(u.pathname)?u.pathname:'/' }catch{return '/';}}
function sendJson(res,obj,status=200){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj));}

export async function handler(req,res){
 try{
  const url=new URL(req.url,'http://localhost');const path=url.pathname;const user=current(req);
  if(req.method==='POST'&&path!=='/api/shopify/webhook'){
   const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host){page(res,'Forbidden','Invalid origin',403);return;}
   if(!origin && req.headers['sec-fetch-site'] && req.headers['sec-fetch-site']!=='same-origin'){page(res,'Forbidden','Invalid request',403);return;}
  }
  if(req.method==='GET'&&path==='/affiliate')return page(res,'Affiliate program','<h1>Join the mission</h1><p>Apply to share Saint Michaels Coffee with your community. All applications are reviewed.</p><a class="button" href="/affiliate/apply">Apply to become an affiliate</a>');
  if(req.method==='GET'&&path==='/affiliate/apply'){
   const required=[['First name','first'],['Last name','last'],['Email','email'],['Phone','phone'],['City','city'],['State','state'],['Country','country']].map(([l,n])=>field(l,n,n==='email'?'email':'text',true)).join('');
   return page(res,'Affiliate application',`<h1>Apply to become an affiliate</h1><form method="post" action="/affiliate/apply">${required}<label>Applicant type${select('applicant_type',['Individual','Business','Organization','Nonprofit'])}</label>${field('Business or organization name','organization')}${['Website','Instagram','Facebook','TikTok','YouTube','X / Twitter','LinkedIn','Other profile'].map((s,i)=>field(s,'profile_'+i,'url')).join('')}<label>Primary platform${select('platform',['Instagram','Facebook','TikTok','YouTube','Website','Podcast','Events','Other'])}</label>${field('Approximate audience size','audience')}<label>Audience or community type${select('audience_type',['Military','Veterans','Law Enforcement','Fire / EMS','Coffee','Fitness','Lifestyle','Business','Nonprofit / Community','Content Creator','General Consumer','Other'])}</label><label>How will you promote us? <textarea name="promotion" required></textarea></label><label>Tell us about yourself or your organization<textarea name="about" required></textarea></label><label>Why would you like to join?<textarea name="why" required></textarea></label><label>How did you hear about us?${select('heard',['Google / Search','Facebook','Instagram','TikTok','YouTube','Friend / Referral','Military / Veteran Community','Law Enforcement / First Responder Community','Event','Existing Customer','Team Member','Other'])}</label>${['I certify that the information is accurate.','Applying does not guarantee acceptance.','I agree to follow the Affiliate Program Terms if accepted.','I understand participation requires approval and can be suspended or terminated under the terms.'].map((s,i)=>`<label><input type="checkbox" name="ack${i}" value="yes" required> ${esc(s)}</label>`).join('')}<button>Submit application</button></form>`);
  }
  if(req.method==='POST'&&path==='/affiliate/apply'){
   const f=form(await body(req));if(!f.first||!f.last||!/^\S+@\S+\.\S+$/.test(f.email||'')||!f.phone||!f.city||!f.state||!f.country||!f.promotion||!f.about||!f.why||![0,1,2,3].every(i=>f['ack'+i]==='yes'))return page(res,'Incomplete','<h1>Please complete all required fields and acknowledgments.</h1>',400);
   if(q('SELECT 1 FROM users WHERE email=?',f.email.toLowerCase()))return page(res,'Application received','<h1>Thank you</h1><p>If your email is eligible, your application will be reviewed.</p>');
   const id=run("INSERT INTO users(email,name,role,status) VALUES(?,?,'affiliate','pending')",f.email.toLowerCase(),`${f.first} ${f.last}`).lastInsertRowid;
   const app=run('INSERT INTO applications(user_id,body) VALUES(?,?)',id,JSON.stringify(f));
   mail(f.email,'Application received','Thank you. We will review your application.');mail(q("SELECT email FROM users WHERE role='admin' LIMIT 1").email,'New affiliate application',`Review application ${app.lastInsertRowid} at /admin/affiliates/application/${app.lastInsertRowid}`);
   return page(res,'Application received','<h1>Application received</h1><p>We will review it and email you an update.</p>');
  }
  if(req.method==='GET'&&path==='/affiliate/login')return page(res,'Sign in',`<h1>Sign in</h1><form method="post" action="/affiliate/login">${field('Email','email','email',true)}${field('Password','password','password',true)}<button>Sign in</button></form>`);
  if(req.method==='POST'&&path==='/affiliate/login'){
   const f=form(await body(req));const u=q('SELECT * FROM users WHERE email=?',(f.email||'').toLowerCase());if(!u||!verifyPassword(f.password||'',u.password)||u.status!=='active')return page(res,'Sign in failed','<h1>Invalid credentials</h1><a href="/affiliate/login">Try again</a>',401);return login(res,u);
  }
  if(req.method==='POST'&&path==='/affiliate/logout'){const c=cookie(req);if(c)run('DELETE FROM sessions WHERE hash=?',sha(c));return redirect(res,'/affiliate',{'Set-Cookie':'sm_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
  if(req.method==='GET'&&path==='/affiliate/activate'){
   const token=url.searchParams.get('token')||'';const t=q("SELECT * FROM tokens WHERE hash=? AND purpose='activate' AND expires>?",sha(token),Date.now());if(!t)return page(res,'Expired','<h1>Activation link expired</h1>',410);
   return page(res,'Activate account',`<h1>Activate account</h1><form method="post" action="/affiliate/activate"><input type="hidden" name="token" value="${esc(token)}">${field('New password (12+ characters)','password','password',true)}<button>Activate</button></form>`);
  }
  if(req.method==='POST'&&path==='/affiliate/activate'){
   const f=form(await body(req));const t=q("SELECT * FROM tokens WHERE hash=? AND purpose='activate' AND expires>?",sha(f.token||''),Date.now());if(!t||!f.password||f.password.length<12)return page(res,'Invalid link','Activation failed or password too short',400);
   run('UPDATE users SET password=?,status=? WHERE id=?',hashPassword(f.password),'active',t.user_id);run('DELETE FROM tokens WHERE hash=?',t.hash);return login(res,q('SELECT * FROM users WHERE id=?',t.user_id));
  }
  if(req.method==='GET'&&path==='/affiliate/dashboard'){
   if(!requireRole(res,user,'affiliate'))return;
   const stats=q('SELECT COUNT(*) clicks,COUNT(DISTINCT visitor) visitors FROM events WHERE user_id=?',user.id);const orders=q("SELECT COUNT(*) orders,COALESCE(SUM(amount),0) revenue FROM orders WHERE user_id=? AND status='paid'",user.id);const commissions=all('SELECT status,COALESCE(SUM(amount),0) amount FROM commissions WHERE user_id=? GROUP BY status',user.id);
   const link=`https://saintmichaelscoffee.com/api/referral?ref=${encodeURIComponent(user.code)}`;
   return page(res,'Affiliate dashboard',`<h1>Welcome, ${esc(user.name)}</h1><div class="grid"><article>Clicks: ${stats.clicks}</article><article>Unique visitors: ${stats.visitors}</article><article>Orders: ${orders.orders}</article><article>Conversion: ${stats.visitors?((orders.orders/stats.visitors)*100).toFixed(1):'0'}%</article><article>Revenue: $${orders.revenue.toFixed(2)}</article></div><h2>Your referral link</h2><input readonly value="${esc(link)}" aria-label="Your referral link"><p>Approved destinations: homepage, shop, foundation, story. Append <code>&amp;to=/shop.html</code> for the shop.</p><p>Type: ${esc(user.kind)} · Rate: ${esc(user.rate)} ${user.rate_type==='percent'?'%':user.rate_type==='fixed'?'per order':''}</p><h2>Commissions</h2>${commissions.map(c=>`<article>${esc(c.status)}: $${c.amount.toFixed(2)}</article>`).join('')||'<p>No commissions yet.</p>'}<p><a href="/affiliate/assets">Asset Library</a></p><form method="post" action="/affiliate/logout"><button>Sign out</button></form>`);
  }
  if(req.method==='GET'&&path==='/affiliate/assets'){
   if(!requireRole(res,user,'affiliate'))return;const agreement=q('SELECT * FROM agreements WHERE active=1');const accepted=q('SELECT 1 FROM acceptance WHERE user_id=? AND version=?',user.id,agreement.version);
   if(!accepted)return page(res,'Asset agreement',`<h1>Brand and asset use agreement · ${esc(agreement.version)}</h1><article>${esc(agreement.body)}</article><form method="post" action="/affiliate/assets/accept"><label><input type="checkbox" name="agree" value="yes" required> I have read and agree to the Brand and Asset Use Agreement.</label><button>Accept and access assets</button></form>`);
   return page(res,'Asset Library',`<h1>Approved Asset Library</h1>${all("SELECT * FROM assets WHERE status='active' ORDER BY id DESC").map(a=>`<article><h2>${esc(a.title)}</h2><p>${esc(a.category)}</p><a href="${esc(a.url)}" rel="noopener noreferrer">Open approved asset</a></article>`).join('')||'<p>No active assets yet.</p>'}`);
  }
  if(req.method==='POST'&&path==='/affiliate/assets/accept'){
   if(!requireRole(res,user,'affiliate'))return;const f=form(await body(req));if(f.agree!=='yes')return page(res,'Agreement required','Please accept the agreement',400);const a=q('SELECT version FROM agreements WHERE active=1');run('INSERT OR IGNORE INTO acceptance(user_id,version,ip) VALUES(?,?,?)',user.id,a.version,req.socket.remoteAddress);audit(user,'agreement.accepted',{version:a.version});return redirect(res,'/affiliate/assets');
  }
  if(req.method==='GET'&&path==='/admin/affiliates'){
   if(!requireRole(res,user,'admin'))return;const apps=all('SELECT applications.*,users.name,users.email FROM applications JOIN users ON users.id=applications.user_id ORDER BY applications.id DESC');const aff=all("SELECT id,name,code,kind,rate_type,rate,status FROM users WHERE role='affiliate' ORDER BY id DESC");const pending=q("SELECT COALESCE(SUM(amount),0) n FROM commissions WHERE status='pending'");
   return page(res,'Admin affiliates',`<h1>Affiliate administration</h1><div class="grid"><article>Applications: ${apps.length}</article><article>Affiliates: ${aff.length}</article><article>Pending commissions: $${pending.n.toFixed(2)}</article></div><h2>Applications</h2><div class="scroll"><table><tr><th>Name</th><th>Email</th><th>Status</th><th>Review</th></tr>${apps.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.email)}</td><td>${esc(a.status)}</td><td><a href="/admin/affiliates/application/${a.id}">Review</a></td></tr>`).join('')}</table></div><h2>Affiliates</h2><div class="scroll"><table><tr><th>Name</th><th>Code</th><th>Type</th><th>Rate</th><th>Status</th><th>Edit</th></tr>${aff.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.code)}</td><td>${esc(a.kind)}</td><td>${esc(a.rate)} ${esc(a.rate_type)}</td><td>${esc(a.status)}</td><td><a href="/admin/affiliates/user/${a.id}">Edit</a></td></tr>`).join('')}</table></div><p><a href="/admin/affiliates/commissions">Commissions</a> · <a href="/admin/affiliates/assets">Assets</a> · <a href="/admin/affiliates/outbox">Local email outbox</a> · <a href="/admin/affiliates/audit">Audit</a></p>`);
  }
  let m=path.match(/^\/admin\/affiliates\/application\/(\d+)$/);
  if(m){if(!requireRole(res,user,'admin'))return;const a=q('SELECT applications.*,users.name,users.email FROM applications JOIN users ON users.id=applications.user_id WHERE applications.id=?',Number(m[1]));if(!a)return page(res,'Missing','Application not found',404);
   if(req.method==='GET'){const data=JSON.parse(a.body);return page(res,'Application',`<h1>${esc(a.name)} · ${esc(a.status)}</h1>${Object.entries(data).map(([key,val])=>`<article><strong>${esc(key)}</strong>: ${/^https?:\/\//.test(val)?`<a href="${esc(val)}" target="_blank" rel="noopener noreferrer">${esc(val)}</a>`:esc(val)}</article>`).join('')}<form method="post"><label>Private admin notes<textarea name="notes">${esc(a.notes)}</textarea></label><label>Decision${select('decision',['pending','more_info','approved','declined'])}</label><label>Code (approval) <input name="code" value="${esc(a.name.replace(/[^a-z]/gi,'').toUpperCase().slice(0,16))}"></label><label>Affiliate type${select('kind',['tracking','commission'])}</label><label>Rate type${select('rate_type',['none','percent','fixed'])}</label>${field('Rate','rate','number')}<button>Save decision</button></form>`);}
   if(req.method==='POST'){const f=form(await body(req));if(!['pending','more_info','approved','declined'].includes(f.decision)||!['tracking','commission'].includes(f.kind)||!['none','percent','fixed'].includes(f.rate_type))return page(res,'Invalid','Invalid settings',400);const rate=Number(f.rate||0);if(!Number.isFinite(rate)||rate<0||rate>100)return page(res,'Invalid','Invalid rate',400);const code=(f.code||'').toUpperCase().trim();if(f.decision==='approved'&&!/^[A-Z0-9_-]{3,32}$/.test(code))return page(res,'Invalid','Code must be 3–32 letters, digits, underscores or dashes',400);
    try{db.exec('BEGIN');run('UPDATE applications SET status=?,notes=? WHERE id=?',f.decision,f.notes||'',a.id);if(f.decision==='approved'){run("UPDATE users SET code=?,kind=?,rate_type=?,rate=?,status='approved' WHERE id=?",code,f.kind,f.kind==='tracking'?'none':f.rate_type,f.kind==='tracking'?0:rate,a.user_id);const token=randomBytes(32).toString('hex');run('INSERT INTO tokens(hash,user_id,purpose,expires) VALUES(?,?,?,?)',sha(token),a.user_id,'activate',Date.now()+48*3600000);mail(a.email,'Affiliate application approved',`Activate your account: http://localhost:${process.env.PORT||3210}/affiliate/activate?token=${token}`);}else if(f.decision==='declined')mail(a.email,'Affiliate application update','Your application was not approved at this time.');else if(f.decision==='more_info')mail(a.email,'More information requested','Please reply to the Saint Michaels Coffee team with additional information.');audit(user,'application.review',{id:a.id,decision:f.decision});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');if(e.code==='ERR_SQLITE_CONSTRAINT_UNIQUE')return page(res,'Duplicate','That code is already taken.',409);throw e;}return redirect(res,'/admin/affiliates');}
  }
  m=path.match(/^\/admin\/affiliates\/user\/(\d+)$/);if(m){if(!requireRole(res,user,'admin'))return;const a=q("SELECT * FROM users WHERE id=? AND role='affiliate'",Number(m[1]));if(!a)return page(res,'Missing','Affiliate not found',404);if(req.method==='GET')return page(res,'Edit affiliate',`<h1>${esc(a.name)}</h1><form method="post"><label>Status${select('status',['active','suspended','terminated'])}</label><label>Type${select('kind',['tracking','commission'])}</label><label>Rate type${select('rate_type',['none','percent','fixed'])}</label>${field('Rate','rate','number')}<button>Save</button></form><p>Current status: ${esc(a.status)} · ${esc(a.rate)} ${esc(a.rate_type)}</p>`);if(req.method==='POST'){const f=form(await body(req));const rate=Number(f.rate);if(!['active','suspended','terminated'].includes(f.status)||!['tracking','commission'].includes(f.kind)||!['none','percent','fixed'].includes(f.rate_type)||!Number.isFinite(rate)||rate<0||rate>100)return page(res,'Invalid','Invalid settings',400);run('UPDATE users SET status=?,kind=?,rate_type=?,rate=? WHERE id=?',f.status,f.kind,f.kind==='tracking'?'none':f.rate_type,f.kind==='tracking'?0:rate,a.id);audit(user,'affiliate.updated',{id:a.id,status:f.status,rate});return redirect(res,'/admin/affiliates');}}
  if(path==='/admin/affiliates/commissions'){if(!requireRole(res,user,'admin'))return;if(req.method==='GET')return page(res,'Commissions',`<h1>Commissions</h1>${all('SELECT commissions.*,users.name FROM commissions JOIN users ON users.id=commissions.user_id ORDER BY updated DESC').map(c=>`<article><strong>${esc(c.name)}</strong> · ${esc(c.shopify_id)} · $${c.amount.toFixed(2)} · ${esc(c.status)}<form method="post"><input type="hidden" name="order" value="${esc(c.shopify_id)}"><label>New status${select('status',['pending','approved','available','paid','held','reversed'])}</label><label>Reason<input name="reason" required></label><button>Update</button></form></article>`).join('')||'<p>No commissions.</p>'}`);if(req.method==='POST'){const f=form(await body(req));if(!['pending','approved','available','paid','held','reversed'].includes(f.status)||!f.reason)return page(res,'Invalid','Status and reason required',400);run('UPDATE commissions SET status=?,updated=CURRENT_TIMESTAMP WHERE shopify_id=?',f.status,f.order);audit(user,'commission.status',{order:f.order,status:f.status,reason:f.reason});return redirect(res,path);}}
  if(path==='/admin/affiliates/assets'){if(!requireRole(res,user,'admin'))return;if(req.method==='GET')return page(res,'Assets',`<h1>Approved assets</h1><form method="post">${field('Title','title','text',true)}${field('Category','category','text',true)}${field('Approved HTTPS URL','url','url',true)}<button>Add asset</button></form>${all('SELECT * FROM assets ORDER BY id DESC').map(a=>`<article>${esc(a.title)} · ${esc(a.status)} <form class="inline" method="post"><input type="hidden" name="asset_id" value="${a.id}">${select('status',['active','archived','disabled'])}<button>Update</button></form></article>`).join('')}`);if(req.method==='POST'){const f=form(await body(req));if(f.asset_id){if(!['active','archived','disabled'].includes(f.status))return page(res,'Invalid','Invalid status',400);run('UPDATE assets SET status=?,version=version+1 WHERE id=?',f.status,Number(f.asset_id));audit(user,'asset.updated',{id:f.asset_id,status:f.status});}else{if(!f.title||!f.category||!/^https:\/\//.test(f.url||''))return page(res,'Invalid','HTTPS URL and title required',400);run('INSERT INTO assets(title,category,url) VALUES(?,?,?)',f.title,f.category,f.url);audit(user,'asset.added',{title:f.title});}return redirect(res,path);}}
  if(req.method==='GET'&&path==='/admin/affiliates/outbox'){if(!requireRole(res,user,'admin'))return;return page(res,'Local outbox',`<h1>Local email outbox (no messages sent)</h1>${all('SELECT * FROM outbox ORDER BY id DESC LIMIT 50').map(x=>`<article><strong>${esc(x.recipient)}</strong> · ${esc(x.subject)}<p>${esc(x.body)}</p></article>`).join('')}`);}
  if(req.method==='GET'&&path==='/admin/affiliates/audit'){if(!requireRole(res,user,'admin'))return;return page(res,'Audit',`<h1>Audit records</h1>${all('SELECT * FROM audit ORDER BY id DESC LIMIT 100').map(x=>`<article>${esc(x.created)} · ${esc(x.action)} · ${esc(x.detail)}</article>`).join('')}`);}
  if(req.method==='GET'&&path==='/api/referral'){
   const code=(url.searchParams.get('ref')||'').toUpperCase();const dest=safePath(url.searchParams.get('to')||'/');const aff=q("SELECT id FROM users WHERE code=? AND status='active'",code);
   if(aff){const visit=randomBytes(32).toString('hex');run('INSERT INTO referral_sessions(hash,user_id,expires) VALUES(?,?,?)',sha(visit),aff.id,Date.now()+30*86400000);run('INSERT INTO events(user_id,visitor) VALUES(?,?)',aff.id,sha(req.headers['user-agent']+':'+req.socket.remoteAddress+':'+new Date().toISOString().slice(0,10)));return redirect(res,dest,{'Set-Cookie':`sm_ref=${visit}; HttpOnly; Path=/; Max-Age=2592000; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`});}
   return redirect(res,dest);
  }
  if(req.method==='POST'&&path==='/api/shopify/cart'){
   await body(req);
   const domain=process.env.SHOPIFY_STORE_DOMAIN||'',variant=process.env.SHOPIFY_VARIANT_ID||'';
   const publicToken=process.env.SHOPIFY_STOREFRONT_TOKEN||'';
   const clientId=process.env.SHOPIFY_CLIENT_ID||'',clientSecret=process.env.SHOPIFY_CLIENT_SECRET||'';
   if(!/^[a-z0-9-]+\.myshopify\.com$/.test(domain)||!(publicToken||(clientId&&clientSecret))||!/^gid:\/\/shopify\/ProductVariant\/\d+$/.test(variant))return sendJson(res,{error:'Shopify checkout is not configured'},503);
   const ref=/(?:^|; )sm_ref=([a-f0-9]{64})/.exec(req.headers.cookie||'')?.[1];
   const affiliate=ref?q("SELECT users.code FROM referral_sessions JOIN users ON users.id=referral_sessions.user_id WHERE referral_sessions.hash=? AND referral_sessions.expires>? AND users.status='active'",sha(ref),Date.now()):null;
   const query='mutation CartCreate($input: CartInput) { cartCreate(input: $input) { cart { checkoutUrl } userErrors { field message } } }';
   const variables={input:{lines:[{merchandiseId:variant,quantity:1}],attributes:affiliate?[{key:'sm_affiliate_code',value:affiliate.code}]:[]}};
   const token=publicToken||await storefrontPrivateToken({domain,clientId,clientSecret});
   const headers={'Content-Type':'application/json',...(publicToken?{'X-Shopify-Storefront-Access-Token':token}:{'Shopify-Storefront-Private-Token':token})};
   const response=await fetch(`https://${domain}/api/2026-07/graphql.json`,{method:'POST',headers,body:JSON.stringify({query,variables})});
   if(!response.ok)return sendJson(res,{error:'Shopify could not create a cart'},502);
   const result=await response.json(),checkout=result.data?.cartCreate?.cart?.checkoutUrl;
   if(result.errors?.length||result.data?.cartCreate?.userErrors?.length||!checkout)return sendJson(res,{error:'Shopify rejected the cart'},502);
   const target=new URL(checkout);const allowed=[domain,process.env.SHOPIFY_CHECKOUT_DOMAIN].filter(Boolean);if(target.protocol!=='https:'||!allowed.includes(target.hostname))return sendJson(res,{error:'Unexpected checkout URL'},502);
   return redirect(res,target.toString());
  }
  if(req.method==='POST'&&path==='/api/shopify/webhook'){
   const raw=await body(req),key=process.env.SHOPIFY_WEBHOOK_SECRET;if(!key)return sendJson(res,{error:'Webhook not configured'},503);const got=req.headers['x-shopify-hmac-sha256']||'',want=createHmac('sha256',key).update(raw).digest('base64');if(got.length!==want.length||!timingSafeEqual(Buffer.from(got),Buffer.from(want)))return sendJson(res,{error:'Invalid signature'},401);
   const topic=req.headers['x-shopify-topic'];if(!['orders/paid','orders/cancelled','refunds/create'].includes(topic))return sendJson(res,{ok:true,ignored:true});const data=JSON.parse(raw);const id=String(topic==='refunds/create'?data.order_id:data.id||'');if(!/^\d+$/.test(id))return sendJson(res,{error:'Invalid order ID'},400);
   if(topic==='orders/paid'){
    // A verified paid order alone is not proof of referral; require server-verifiable order attribution.
    const attr=(data.note_attributes||[]).find(a=>a.name==='sm_affiliate_code')?.value||'';const aff=q("SELECT * FROM users WHERE code=? AND status='active'",String(attr).toUpperCase());if(!aff)return sendJson(res,{ok:true,attributed:false});
    const amount=Number(data.current_subtotal_price||data.subtotal_price);if(!Number.isFinite(amount)||amount<0)return sendJson(res,{error:'Invalid subtotal'},400);
    db.exec('BEGIN');try{run("INSERT INTO orders(shopify_id,user_id,amount,status) VALUES(?,?,?,'paid') ON CONFLICT(shopify_id) DO UPDATE SET amount=excluded.amount,status='paid',updated=CURRENT_TIMESTAMP",id,aff.id,amount);const commission=aff.kind==='commission'?(aff.rate_type==='percent'?amount*aff.rate/100:aff.rate_type==='fixed'?aff.rate:0):0;run("INSERT INTO commissions(shopify_id,user_id,amount,status) VALUES(?,?,?,'pending') ON CONFLICT(shopify_id) DO NOTHING",id,aff.id,Math.round(commission*100)/100);audit(null,'order.paid',{id,affiliate:aff.id,amount});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return sendJson(res,{ok:true,attributed:true});
   }
   const o=q('SELECT * FROM orders WHERE shopify_id=?',id);if(!o)return sendJson(res,{ok:true,attributed:false});
   const refunded=topic==='refunds/create'?Number((data.transactions||[]).filter(t=>t.kind==='refund').reduce((sum,t)=>sum+Number(t.amount||0),0)):o.amount;
   db.exec('BEGIN');try{if(topic==='orders/cancelled'){run("UPDATE orders SET status='cancelled',updated=CURRENT_TIMESTAMP WHERE shopify_id=?",id);run("UPDATE commissions SET status='reversed',amount=0,updated=CURRENT_TIMESTAMP WHERE shopify_id=?",id);}else{const newAmount=Math.max(0,o.amount-refunded);run('UPDATE orders SET amount=?,updated=CURRENT_TIMESTAMP WHERE shopify_id=?',newAmount,id);run("UPDATE commissions SET amount=MAX(0,amount-?),status=CASE WHEN ?<=0 THEN 'reversed' ELSE 'held' END,updated=CURRENT_TIMESTAMP WHERE shopify_id=?",Math.round(refunded/o.amount*(q('SELECT amount FROM commissions WHERE shopify_id=?',id)?.amount||0)*100)/100,newAmount,id);}audit(null,'order.adjusted',{id,topic,refunded});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return sendJson(res,{ok:true});
  }
  return page(res,'Not found','<h1>Page not found</h1>',404);
 }catch(e){console.error(e);return page(res,'Error','<h1>Something went wrong</h1>',500);}
}
if(process.argv[1]===fileURLToPath(import.meta.url)){http.createServer(handler).listen(Number(process.env.PORT||3210),()=>console.log(`Affiliate prototype http://localhost:${process.env.PORT||3210}`));}
